# Generated by Django 3.2.4 on 2021-06-21 17:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_title', models.CharField(blank=True, max_length=100, null=True)),
                ('crime_description', models.TextField(blank=True, max_length=300, null=True)),
                ('crime_location', models.CharField(blank=True, default='Jigawa', max_length=100, null=True)),
                ('lga', models.CharField(blank=True, choices=[('dutse', 'DUTSE'), ('bkd', 'BIRNINKUDU'), ('hadejia', 'HADEJIA'), ('ringim', 'RINGIM'), ('gumel', 'GUMEL'), ('kazaure', 'KAZAURE')], default='dutse', max_length=32, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('treated', models.BooleanField(blank=True, default=False, null=True)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
